name: Build on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOS: linux
      GOARCH: arm
      CGO_ENABLED: 0
      VERSION: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Patch Go 1.24
        run: |
          mkdir -p /opt
          (cd /opt && wget https://go.dev/dl/go1.24.13.src.tar.gz && tar xf go1.24.13.src.tar.gz)
          cp .github/netpoll_epoll.go /opt/go/src/runtime/netpoll_epoll.go
          (cd /opt/go/src && ./make.bash)
          echo "/opt/go/bin" >> "$GITHUB_PATH"

      - name: Build binary
        run: |
          go build \
            -trimpath \
            -ldflags="-X github.com/paulzzh/komari-agent-er2260t/update.CurrentVersion=${VERSION}" \
            -o komari-agent-linux-arm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: komari-agent-linux-arm
          path: komari-agent-linux-arm