name: Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-attach:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Patch Go 1.24
        run: |
          mkdir -p /opt
          (cd /opt && wget https://go.dev/dl/go1.24.13.src.tar.gz && tar xf go1.24.13.src.tar.gz)
          cp .github/netpoll_epoll.go /opt/go/src/runtime/netpoll_epoll.go
          (cd /opt/go/src && ./make.bash)
          echo "/opt/go/bin" >> "$GITHUB_PATH"

      - name: Build binary
        run: |
          export GOOS=linux
          export GOARCH=arm
          export CGO_ENABLED=0
          go build \
            -trimpath \
            -ldflags="-X github.com/paulzzh/komari-agent-er2260t/update.CurrentVersion=${VERSION}" \
            -o komari-agent-linux-arm

      - name: Upload binary to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload \
            ${{ github.event.release.tag_name }} \
            komari-agent-linux-arm \
            --repo ${{ github.repository }}